#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "append ITEM# 'TEXT TO APPEND'"
    echo "  For each ITEM#, calls command append."
    echo ""
    exit
}

for append; do true; done

for i in $(seq 1 `expr $# - 1`); do
    #$TODO_SH command append ${!i} $append;
    echo "command append ${!i} $append";
done